"""empty message

Revision ID: 895813ae4dfd
Revises: 
Create Date: 2022-02-01 10:58:45.076207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895813ae4dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###
